### ISSUE TITLE
Write a beautiful README.md: add Mockups to illustrate the project!

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/ATS-SPC-B#1]
- https://balsamiq.com
- https://guides.github.com/features/mastering-markdown/

**Comment by yvan-sraka** [comment]
Explain how to launch the project :smile:!

**Comment by yvan-sraka** [comment]
Convert mockup from `.pdf` to `.png` and add images to the `README.md` :wink:!

**Comment by yvan-sraka** [comment]
Your mockups are ugly, replace by screenshots of the app!

**Comment by yvan-sraka** [comment]
Why the `README.md` of the project describe the template you use?

**Comment by yvan-sraka** [comment]
Do you use `NodeJS` with `Gulp.js` because I see `gulpfile.js` and `package.json` conf files..

**Comment by amare16** [comment]
Ohh, the README.md file is a copy and paste mistake, thanks.

**Comment by amare16** [comment]
We didn't use NodeJs but those files are coming with the template. Already i deleted.

**Comment by amare16** [comment]
We already corrected.
Merci :smile:
