### ISSUE TITLE
Protect admin section of the app with .htaccess and .htpasswd Apache configuration files

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/ATS-SPC-B#5]
- https://openclassrooms.com/courses/concevez-votre-site-web-avec-php-et-mysql/proteger-un-dossier-avec-un-htaccess
- https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04

**Comment by kalaaji** [comment]
Done! try it :smile:

**Comment by yvan-sraka** [comment]
Did you fix it?
